import { useEffect, useMemo, useState } from "react";
import { Layout } from "@/components/Layout";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { Activity, BarChart3, Bell, CalendarCheck, CheckCircle2, ClipboardList, CreditCard, Dumbbell, Loader2, LogOut, Plus, RefreshCw, Settings, UserCheck, Users, XCircle, type LucideIcon } from "lucide-react";

type Gym = { id: string; name: string; city: string | null; country?: string | null; status: string; email?: string | null; phone?: string | null; gym_type?: string | null; member_capacity?: number | null; };
type Member = { id: string; gym_id: string; full_name: string; email: string | null; phone: string | null; membership_tier: string | null; active: boolean; joined_at: string; };
type AttendanceRow = { id: string; gym_id: string; member_id: string; checked_in_at: string; checked_out_at: string | null; method: string | null; };
type EquipmentRow = { id: string; gym_id: string; name: string; category: string | null; quantity: number; status: string; notes: string | null; };
type Lead = { id: string; gym_id: string; full_name: string; phone: string | null; email: string | null; source: string | null; status: string; notes: string | null; created_at: string; };
type Payment = { id: string; gym_id: string; member_id: string | null; amount: number; currency: string; status: string; method: string | null; paid_at: string; notes: string | null; };
type Announcement = { id: string; gym_id: string; title: string; body: string; audience: string; is_published: boolean; created_at: string; };
type TabKey = "overview" | "members" | "attendance" | "equipment" | "leads" | "payments" | "announcements" | "reports" | "settings";

const tabs: { key: TabKey; label: string; icon: LucideIcon }[] = [
  { key: "overview", label: "Overview", icon: BarChart3 }, { key: "members", label: "Members", icon: Users }, { key: "attendance", label: "Attendance", icon: CalendarCheck }, { key: "equipment", label: "Equipment", icon: Dumbbell },
  { key: "leads", label: "Leads", icon: UserCheck }, { key: "payments", label: "Payments", icon: CreditCard }, { key: "announcements", label: "Announcements", icon: Bell }, { key: "reports", label: "Reports", icon: ClipboardList }, { key: "settings", label: "Settings", icon: Settings },
];

const todayKey = () => new Date().toISOString().slice(0, 10);
const formatDate = (value?: string | null) => value ? new Date(value).toLocaleString() : "—";
const sameMonth = (value: string) => { const d = new Date(value); const now = new Date(); return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear(); };
const money = (amount: number, currency = "INR") => new Intl.NumberFormat("en-IN", { style: "currency", currency }).format(Number(amount || 0));
const actionClass = "inline-flex items-center gap-2 border border-separator px-4 py-3 text-xs uppercase tracking-widest hover:bg-hover-bg text-left";

export default function OwnerWorkspace() {
  const db = supabase as any;
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [tab, setTab] = useState<TabKey>("overview");
  const [gym, setGym] = useState<Gym | null>(null); const [members, setMembers] = useState<Member[]>([]); const [attendance, setAttendance] = useState<AttendanceRow[]>([]); const [equipment, setEquipment] = useState<EquipmentRow[]>([]);
  const [leads, setLeads] = useState<Lead[]>([]); const [payments, setPayments] = useState<Payment[]>([]); const [announcements, setAnnouncements] = useState<Announcement[]>([]);
  const [memberForm, setMemberForm] = useState({ full_name: "", email: "", phone: "", membership_tier: "Monthly" }); const [attendanceMemberId, setAttendanceMemberId] = useState(""); const [equipmentForm, setEquipmentForm] = useState({ name: "", category: "Strength", quantity: 1, notes: "" });
  const [leadForm, setLeadForm] = useState({ full_name: "", phone: "", email: "", source: "Walk-in", notes: "" }); const [paymentForm, setPaymentForm] = useState({ member_id: "", amount: "", method: "cash", notes: "" }); const [announcementForm, setAnnouncementForm] = useState({ title: "", body: "", audience: "all_members" });

  const activeMembers = useMemo(() => members.filter((m) => m.active !== false), [members]); const todayAttendance = useMemo(() => attendance.filter((a) => a.checked_in_at?.slice(0, 10) === todayKey()), [attendance]); const openAttendance = useMemo(() => attendance.filter((a) => !a.checked_out_at), [attendance]); const monthlyAttendance = useMemo(() => attendance.filter((a) => sameMonth(a.checked_in_at)), [attendance]); const monthlyRevenue = useMemo(() => payments.filter((p) => sameMonth(p.paid_at) && p.status !== "failed").reduce((sum, p) => sum + Number(p.amount || 0), 0), [payments]);

  const load = async () => {
    setLoading(true);
    try {
      const { data: sessionData } = await supabase.auth.getSession(); const user = sessionData.session?.user; if (!user) { setGym(null); return; }
      const { data: roleRows } = await db.from("user_roles").select("gym_id").eq("user_id", user.id).eq("role", "gym_owner").limit(1);
      let gymRow: Gym | null = null; const linkedGymId = roleRows?.[0]?.gym_id;
      if (linkedGymId) { const { data } = await db.from("gyms").select("id,name,city,country,status,email,phone,gym_type,member_capacity").eq("id", linkedGymId).maybeSingle(); gymRow = data; }
      if (!gymRow) { const { data } = await db.from("gyms").select("id,name,city,country,status,email,phone,gym_type,member_capacity").eq("owner_id", user.id).order("created_at", { ascending: false }).limit(1).maybeSingle(); gymRow = data; }
      if (!gymRow) { setGym(null); return; } setGym(gymRow);
      const safe = async (q: Promise<any>) => { const r = await q; return r?.error ? [] : (r?.data ?? []); };
      const [memberRows, attendanceRows, equipmentRows, leadRows, paymentRows, announcementRows] = await Promise.all([
        safe(db.from("gym_members").select("*").eq("gym_id", gymRow.id).order("joined_at", { ascending: false })), safe(db.from("attendance").select("*").eq("gym_id", gymRow.id).order("checked_in_at", { ascending: false }).limit(200)), safe(db.from("equipment").select("*").eq("gym_id", gymRow.id).order("created_at", { ascending: false })), safe(db.from("gym_leads").select("*").eq("gym_id", gymRow.id).order("created_at", { ascending: false })), safe(db.from("gym_payments").select("*").eq("gym_id", gymRow.id).order("paid_at", { ascending: false }).limit(200)), safe(db.from("gym_announcements").select("*").eq("gym_id", gymRow.id).order("created_at", { ascending: false })),
      ]);
      setMembers(memberRows); setAttendance(attendanceRows); setEquipment(equipmentRows); setLeads(leadRows); setPayments(paymentRows); setAnnouncements(announcementRows);
    } catch (error) { toast.error("Could not load gym workspace", { description: error instanceof Error ? error.message : "Please refresh and try again." }); } finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []);
  const logout = async () => { await supabase.auth.signOut(); window.location.href = "/"; };
  const save = async (work: Promise<any>, success: string, reset?: () => void) => { setSaving(true); const { error } = await work; setSaving(false); if (error) return toast.error("Action failed", { description: error.message }); toast.success(success); reset?.(); load(); };
  const addMember = (e: React.FormEvent) => { e.preventDefault(); if (!gym || !memberForm.full_name.trim()) return; save(db.from("gym_members").insert({ gym_id: gym.id, full_name: memberForm.full_name.trim(), email: memberForm.email.trim() || null, phone: memberForm.phone.trim() || null, membership_tier: memberForm.membership_tier.trim() || "Monthly", active: true }), "Member added", () => setMemberForm({ full_name: "", email: "", phone: "", membership_tier: "Monthly" })); };
  const toggleMember = (member: Member) => save(db.from("gym_members").update({ active: !member.active }).eq("id", member.id).eq("gym_id", member.gym_id), member.active ? "Member deactivated" : "Member activated");
  const checkIn = (e: React.FormEvent) => { e.preventDefault(); if (!gym || !attendanceMemberId) return; save(db.from("attendance").insert({ gym_id: gym.id, member_id: attendanceMemberId, method: "manual", checked_in_at: new Date().toISOString() }), "Member checked in", () => setAttendanceMemberId("")); };
  const checkOut = (row: AttendanceRow) => save(db.from("attendance").update({ checked_out_at: new Date().toISOString() }).eq("id", row.id).eq("gym_id", row.gym_id), "Member checked out");
  const addEquipment = (e: React.FormEvent) => { e.preventDefault(); if (!gym || !equipmentForm.name.trim()) return; save(db.from("equipment").insert({ gym_id: gym.id, name: equipmentForm.name.trim(), category: equipmentForm.category.trim() || null, quantity: Number(equipmentForm.quantity || 1), status: "active", notes: equipmentForm.notes.trim() || null }), "Equipment added", () => setEquipmentForm({ name: "", category: "Strength", quantity: 1, notes: "" })); };
  const addLead = (e: React.FormEvent) => { e.preventDefault(); if (!gym || !leadForm.full_name.trim()) return; save(db.from("gym_leads").insert({ gym_id: gym.id, full_name: leadForm.full_name.trim(), phone: leadForm.phone || null, email: leadForm.email || null, source: leadForm.source || "manual", status: "new", notes: leadForm.notes || null }), "Lead added", () => setLeadForm({ full_name: "", phone: "", email: "", source: "Walk-in", notes: "" })); };
  const updateLeadStatus = (lead: Lead, status: string) => save(db.from("gym_leads").update({ status, updated_at: new Date().toISOString() }).eq("id", lead.id).eq("gym_id", lead.gym_id), "Lead updated");
  const addPayment = (e: React.FormEvent) => { e.preventDefault(); if (!gym || !paymentForm.amount) return; save(db.from("gym_payments").insert({ gym_id: gym.id, member_id: paymentForm.member_id || null, amount: Number(paymentForm.amount), currency: "INR", status: "paid", method: paymentForm.method || "cash", notes: paymentForm.notes || null, paid_at: new Date().toISOString() }), "Payment recorded", () => setPaymentForm({ member_id: "", amount: "", method: "cash", notes: "" })); };
  const addAnnouncement = (e: React.FormEvent) => { e.preventDefault(); if (!gym || !announcementForm.title.trim() || !announcementForm.body.trim()) return; save(db.from("gym_announcements").insert({ gym_id: gym.id, title: announcementForm.title.trim(), body: announcementForm.body.trim(), audience: announcementForm.audience, is_published: true }), "Announcement published", () => setAnnouncementForm({ title: "", body: "", audience: "all_members" })); };
  const toggleAnnouncement = (a: Announcement) => save(db.from("gym_announcements").update({ is_published: !a.is_published, updated_at: new Date().toISOString() }).eq("id", a.id).eq("gym_id", a.gym_id), a.is_published ? "Announcement hidden" : "Announcement published");
  const memberName = (id?: string | null) => members.find((m) => m.id === id)?.full_name || "Walk-in / unassigned";

  return <Layout hideFooter><section className="container-wide py-8 md:py-10">{loading ? <div className="py-24 flex justify-center"><Loader2 className="animate-spin text-accent" /></div> : !gym ? <div className="max-w-xl py-20"><h1 className="font-display text-3xl font-bold mb-3">Access not active</h1><p className="text-foreground/70">This account is not linked to an active approved gym. Validate your access code or contact support.</p></div> : <>
    <div className="flex flex-col gap-6 border-b border-separator pb-8 md:flex-row md:items-end md:justify-between"><div><p className="text-label mb-2">Gym owner workspace</p><h1 className="font-display text-4xl md:text-6xl font-bold tracking-[-0.04em]">{gym.name}</h1><p className="mt-3 text-sm text-foreground/60">{gym.city || "City not set"} · {gym.status}</p></div><div className="flex flex-wrap gap-2"><button onClick={load} className="inline-flex items-center gap-2 px-4 py-2 border border-separator text-xs uppercase tracking-widest hover:bg-hover-bg"><RefreshCw size={14} /> Refresh</button><button onClick={logout} className="inline-flex items-center gap-2 px-4 py-2 border border-separator text-xs uppercase tracking-widest hover:bg-hover-bg"><LogOut size={14} /> Sign out</button></div></div>
    <div className="my-8 grid grid-cols-2 lg:grid-cols-5 gap-px bg-separator border border-separator"><Metric icon={Users} label="Active members" value={activeMembers.length} /><Metric icon={CalendarCheck} label="Today check-ins" value={todayAttendance.length} /><Metric icon={UserCheck} label="New leads" value={leads.filter((l) => l.status === "new").length} /><Metric icon={CreditCard} label="Monthly revenue" value={monthlyRevenue} moneyValue /><Metric icon={Dumbbell} label="Equipment" value={equipment.length} /></div>
    <div className="mb-8 flex gap-2 overflow-x-auto pb-2">{tabs.map((item) => <button key={item.key} onClick={() => setTab(item.key)} className={`inline-flex items-center gap-2 border px-4 py-3 text-xs uppercase tracking-widest whitespace-nowrap ${tab === item.key ? "border-accent bg-accent text-accent-foreground" : "border-separator text-foreground/70 hover:bg-hover-bg"}`}><item.icon size={14} /> {item.label}</button>)}</div>
    {tab === "overview" && <div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_360px]"><Panel title="Today at a glance"><div className="grid md:grid-cols-4 gap-px bg-separator border border-separator"><MiniStat label="Members" value={`${activeMembers.length}/${gym.member_capacity || "∞"}`} /><MiniStat label="Check-ins today" value={String(todayAttendance.length)} /><MiniStat label="Open leads" value={String(leads.filter((l) => l.status !== "converted").length)} /><MiniStat label="Revenue this month" value={money(monthlyRevenue)} /></div></Panel><Panel title="Quick actions"><div className="grid gap-3"><button onClick={() => setTab("members")} className={actionClass}><Plus size={15} /> Add member</button><button onClick={() => setTab("attendance")} className={actionClass}><UserCheck size={15} /> Manual check-in</button><button onClick={() => setTab("leads")} className={actionClass}><UserCheck size={15} /> Add lead</button><button onClick={() => setTab("payments")} className={actionClass}><CreditCard size={15} /> Record payment</button><button onClick={() => setTab("announcements")} className={actionClass}><Bell size={15} /> Publish announcement</button></div></Panel></div>}
    {tab === "members" && <TwoCol title="Add member"><form onSubmit={addMember} className="space-y-4"><Input label="Full name" value={memberForm.full_name} onChange={(v) => setMemberForm({ ...memberForm, full_name: v })} required /><Input label="Email" value={memberForm.email} onChange={(v) => setMemberForm({ ...memberForm, email: v })} type="email" /><Input label="Phone" value={memberForm.phone} onChange={(v) => setMemberForm({ ...memberForm, phone: v })} /><Input label="Membership tier" value={memberForm.membership_tier} onChange={(v) => setMemberForm({ ...memberForm, membership_tier: v })} /><Submit saving={saving}>Save member</Submit></form></TwoCol>} {tab === "members" && <ListPanel title="Members" empty="No members added yet.">{members.map((m) => <MemberRow key={m.id} member={m} onToggle={() => toggleMember(m)} />)}</ListPanel>}
    {tab === "attendance" && <TwoCol title="Manual check-in"><form onSubmit={checkIn} className="space-y-4"><Select label="Member" value={attendanceMemberId} onChange={setAttendanceMemberId} options={activeMembers.map((m) => [m.id, m.full_name])} /><Submit saving={saving}>Check in</Submit></form></TwoCol>} {tab === "attendance" && <ListPanel title="Recent attendance" empty="No attendance logs yet.">{attendance.map((r) => <AttendanceItem key={r.id} row={r} name={memberName(r.member_id)} onCheckout={() => checkOut(r)} />)}</ListPanel>}
    {tab === "equipment" && <TwoCol title="Add equipment"><form onSubmit={addEquipment} className="space-y-4"><Input label="Name" value={equipmentForm.name} onChange={(v) => setEquipmentForm({ ...equipmentForm, name: v })} required /><Input label="Category" value={equipmentForm.category} onChange={(v) => setEquipmentForm({ ...equipmentForm, category: v })} /><Input label="Quantity" type="number" value={String(equipmentForm.quantity)} onChange={(v) => setEquipmentForm({ ...equipmentForm, quantity: Number(v) })} /><Input label="Notes" value={equipmentForm.notes} onChange={(v) => setEquipmentForm({ ...equipmentForm, notes: v })} /><Submit saving={saving}>Save equipment</Submit></form></TwoCol>} {tab === "equipment" && <ListPanel title="Equipment inventory" empty="No equipment added yet.">{equipment.map((i) => <EquipmentItem key={i.id} item={i} />)}</ListPanel>}
    {tab === "leads" && <TwoCol title="Add lead"><form onSubmit={addLead} className="space-y-4"><Input label="Full name" value={leadForm.full_name} onChange={(v) => setLeadForm({ ...leadForm, full_name: v })} required /><Input label="Phone" value={leadForm.phone} onChange={(v) => setLeadForm({ ...leadForm, phone: v })} /><Input label="Email" value={leadForm.email} onChange={(v) => setLeadForm({ ...leadForm, email: v })} /><Input label="Source" value={leadForm.source} onChange={(v) => setLeadForm({ ...leadForm, source: v })} /><Input label="Notes" value={leadForm.notes} onChange={(v) => setLeadForm({ ...leadForm, notes: v })} /><Submit saving={saving}>Save lead</Submit></form></TwoCol>} {tab === "leads" && <ListPanel title="Leads pipeline" empty="No leads yet.">{leads.map((l) => <LeadItem key={l.id} lead={l} onStatus={(s) => updateLeadStatus(l, s)} />)}</ListPanel>}
    {tab === "payments" && <TwoCol title="Record payment"><form onSubmit={addPayment} className="space-y-4"><Select label="Member" value={paymentForm.member_id} onChange={(v) => setPaymentForm({ ...paymentForm, member_id: v })} options={members.map((m) => [m.id, m.full_name])} includeEmpty="Walk-in / unassigned" /><Input label="Amount" type="number" value={paymentForm.amount} onChange={(v) => setPaymentForm({ ...paymentForm, amount: v })} required /><Input label="Method" value={paymentForm.method} onChange={(v) => setPaymentForm({ ...paymentForm, method: v })} /><Input label="Notes" value={paymentForm.notes} onChange={(v) => setPaymentForm({ ...paymentForm, notes: v })} /><Submit saving={saving}>Record payment</Submit></form></TwoCol>} {tab === "payments" && <ListPanel title="Payment ledger" empty="No payments recorded yet.">{payments.map((p) => <PaymentItem key={p.id} payment={p} name={memberName(p.member_id)} />)}</ListPanel>}
    {tab === "announcements" && <TwoCol title="Publish announcement"><form onSubmit={addAnnouncement} className="space-y-4"><Input label="Title" value={announcementForm.title} onChange={(v) => setAnnouncementForm({ ...announcementForm, title: v })} required /><Input label="Audience" value={announcementForm.audience} onChange={(v) => setAnnouncementForm({ ...announcementForm, audience: v })} /><Textarea label="Message" value={announcementForm.body} onChange={(v) => setAnnouncementForm({ ...announcementForm, body: v })} /><Submit saving={saving}>Publish</Submit></form></TwoCol>} {tab === "announcements" && <ListPanel title="Announcements" empty="No announcements yet.">{announcements.map((a) => <AnnouncementItem key={a.id} item={a} onToggle={() => toggleAnnouncement(a)} />)}</ListPanel>}
    {tab === "reports" && <Panel title="Reports"><div className="grid md:grid-cols-2 lg:grid-cols-5 gap-px bg-separator border border-separator mb-8"><MiniStat label="Total members" value={String(members.length)} /><MiniStat label="Inactive members" value={String(members.filter((m) => m.active === false).length)} /><MiniStat label="Monthly check-ins" value={String(monthlyAttendance.length)} /><MiniStat label="Revenue" value={money(monthlyRevenue)} /><MiniStat label="Open leads" value={String(leads.filter((l) => l.status !== "converted").length)} /></div><p className="text-sm text-foreground/65 leading-relaxed">Exports and payment gateway settlement reports can be connected after Razorpay/Stripe production keys are finalized.</p></Panel>}
    {tab === "settings" && <Panel title="Gym settings"><div className="grid md:grid-cols-2 gap-px bg-separator border border-separator"><MiniStat label="Gym" value={gym.name} /><MiniStat label="Type" value={gym.gym_type || "Not set"} /><MiniStat label="Email" value={gym.email || "Not set"} /><MiniStat label="Phone" value={gym.phone || "Not set"} /></div></Panel>}
  </>}</section></Layout>;
}

function Metric({ icon: Icon, label, value, moneyValue }: { icon: LucideIcon; label: string; value: number; moneyValue?: boolean }) { return <div className="bg-background p-5 md:p-6"><Icon className="text-accent mb-5" size={20} /><p className="text-label mb-2">{label}</p><p className="font-display text-3xl md:text-4xl font-bold tracking-[-0.04em]">{moneyValue ? money(value) : value}</p></div>; }
function MiniStat({ label, value }: { label: string; value: string }) { return <div className="bg-background p-5"><p className="text-label mb-2">{label}</p><p className="font-display text-2xl font-bold break-words">{value}</p></div>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="border border-separator bg-hover-bg/20 p-5 md:p-6"><p className="text-label mb-5">{title}</p>{children}</section>; }
function TwoCol({ title, children }: { title: string; children: React.ReactNode }) { return <div className="grid gap-8 lg:grid-cols-[380px_minmax(0,1fr)]"><Panel title={title}>{children}</Panel></div>; }
function ListPanel({ title, empty, children }: { title: string; empty: string; children: React.ReactNode }) { return <div className="mt-8"><Panel title={title}><Rows empty={empty}>{children}</Rows></Panel></div>; }
function Rows({ children, empty }: { children: React.ReactNode; empty: string }) { const count = Array.isArray(children) ? children.filter(Boolean).length : children ? 1 : 0; return <div className="border border-separator divide-y divide-separator">{count ? children : <div className="p-6 text-sm text-muted-foreground">{empty}</div>}</div>; }
function Input({ label, value, onChange, type = "text", required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="block space-y-2"><span className="text-xs uppercase tracking-widest text-foreground/60">{label}</span><input className="lv-input" type={type} value={value} onChange={(e) => onChange(e.target.value)} required={required} /></label>; }
function Textarea({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block space-y-2"><span className="text-xs uppercase tracking-widest text-foreground/60">{label}</span><textarea className="lv-input min-h-28" value={value} onChange={(e) => onChange(e.target.value)} required /></label>; }
function Select({ label, value, onChange, options, includeEmpty = "Select…" }: { label: string; value: string; onChange: (value: string) => void; options: string[][]; includeEmpty?: string }) { return <label className="block space-y-2"><span className="text-xs uppercase tracking-widest text-foreground/60">{label}</span><select className="lv-input" value={value} onChange={(e) => onChange(e.target.value)}><option value="">{includeEmpty}</option>{options.map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></label>; }
function Submit({ saving, children }: { saving: boolean; children: React.ReactNode }) { return <button disabled={saving} className="w-full inline-flex justify-center gap-2 bg-accent px-5 py-3 text-xs font-semibold uppercase tracking-widest text-accent-foreground disabled:opacity-50">{saving && <Loader2 size={14} className="animate-spin" />}{children}</button>; }
function MemberRow({ member, onToggle }: { member: Member; onToggle: () => void }) { return <div className="p-4 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="font-medium">{member.full_name}</p><p className="text-xs text-muted-foreground">{member.email || "No email"} · {member.phone || "No phone"} · {member.membership_tier || "No plan"}</p></div><button onClick={onToggle} className={`inline-flex items-center gap-2 px-3 py-2 border text-xs uppercase tracking-widest ${member.active ? "border-accent/40 text-accent" : "border-destructive/40 text-destructive"}`}>{member.active ? <CheckCircle2 size={14} /> : <XCircle size={14} />}{member.active ? "Active" : "Inactive"}</button></div>; }
function AttendanceItem({ row, name, onCheckout }: { row: AttendanceRow; name: string; onCheckout: () => void }) { return <div className="p-4 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="font-medium">{name}</p><p className="text-xs text-muted-foreground">In: {formatDate(row.checked_in_at)} · Out: {formatDate(row.checked_out_at)}</p></div>{!row.checked_out_at && <button onClick={onCheckout} className="inline-flex items-center justify-center gap-2 bg-accent px-3 py-2 text-xs uppercase tracking-widest text-accent-foreground">Check out</button>}</div>; }
function EquipmentItem({ item }: { item: EquipmentRow }) { return <div className="p-4"><p className="font-medium">{item.name}</p><p className="text-xs text-muted-foreground">{item.category || "Uncategorized"} · Qty {item.quantity} · {item.status}</p>{item.notes && <p className="mt-2 text-sm text-foreground/60">{item.notes}</p>}</div>; }
function LeadItem({ lead, onStatus }: { lead: Lead; onStatus: (status: string) => void }) { return <div className="p-4 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="font-medium">{lead.full_name}</p><p className="text-xs text-muted-foreground">{lead.phone || "No phone"} · {lead.email || "No email"} · {lead.source || "manual"} · {lead.status}</p>{lead.notes && <p className="mt-2 text-sm text-foreground/60">{lead.notes}</p>}</div><div className="flex gap-2"><button onClick={() => onStatus("contacted")} className="px-3 py-2 border border-separator text-xs uppercase">Contacted</button><button onClick={() => onStatus("converted")} className="px-3 py-2 bg-accent text-accent-foreground text-xs uppercase">Converted</button></div></div>; }
function PaymentItem({ payment, name }: { payment: Payment; name: string }) { return <div className="p-4"><p className="font-medium">{money(payment.amount, payment.currency)} · {name}</p><p className="text-xs text-muted-foreground">{payment.method || "manual"} · {payment.status} · {formatDate(payment.paid_at)}</p>{payment.notes && <p className="mt-2 text-sm text-foreground/60">{payment.notes}</p>}</div>; }
function AnnouncementItem({ item, onToggle }: { item: Announcement; onToggle: () => void }) { return <div className="p-4 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="font-medium">{item.title}</p><p className="text-sm text-foreground/60">{item.body}</p><p className="mt-1 text-xs text-muted-foreground">{item.audience} · {item.is_published ? "published" : "hidden"} · {formatDate(item.created_at)}</p></div><button onClick={onToggle} className="px-3 py-2 border border-separator text-xs uppercase tracking-widest">{item.is_published ? "Hide" : "Publish"}</button></div>; }
